FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/QUEENNICKYMDv1/QUEEN-NICKY-MD-ERROR-FIX-v1 /root/MR-DUMIDU
WORKDIR /root/MR-DUMIDU/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
